### ISSUE TITLE
Build fail 

### ISSUE THREAD

**Issue by DrSnail** [daboross/screeps-starter-python#19]
`The path python3.5 (from --python=python3.5) does not exist
Traceback (most recent call last):
  File "build.py", line 345, in <module>
    main()
  File "build.py", line 334, in main
    install_env(config)
  File "build.py", line 290, in install_env
    .format(ret, "' '".join(args), config.base_dir))
Exception: virtualenv failed. exit code: 3. command line 'D:\Programs\Anaconda\python.exe' '-m' 'virtualenv' '-p' 'python3.5' '--system-site-packages' 'd:\Programs\Anaconda\envs\screeps\screeps-starter-python-update-transcrypt\env'. working dir: 'd:\Programs\Anaconda\envs\screeps\screeps-starter-python-update-transcrypt'.`
How to fix it?

**Comment by jim-hart** [comment]
@DrSnail, try providing the full path to the python switch: e.g. `--python=D:\Programs\Anaconda\python.exe` assuming the above is the path to your default python interpreter
