### ISSUE TITLE
build failed under Windows using conda

### ISSUE THREAD

**Issue by ForsetiSss** [daboross/screeps-starter-python#21]
(screeps) C:\Users\Forseti>cd screeps-starter-python-master

(screeps) C:\Users\Forseti\screeps-starter-python-master>python build.py
Traceback (most recent call last):
  File "build.py", line 334, in <module>
    main()
  File "build.py", line 322, in main
    config = load_config(base_dir)
  File "build.py", line 133, in load_config
    with open(os.path.join(base_dir, config_file)) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Forseti\\scr
eeps-starter-python-master\\config.json'

**Comment by ForsetiSss** [comment]
the solution is mentioned in the gitbook
