### ISSUE TITLE
build fail with syntax error:

### ISSUE THREAD

**Issue by d-ornen** [daboross/screeps-starter-python#25]
python version: 3.5 and 3.6. Both failed on  Manjaro 18-th version

`running transcrypt...
Traceback (most recent call last):
  File "/home/jus/build/screeps-starter-python/env/bin/transcrypt", line 5, in <module>
    from transcrypt.__main__ import main
  File "/home/jus/build/screeps-starter-python/env/lib/python3.7/site-packages/transcrypt/__main__.py", line 53, in <module>
    from org.transcrypt import compiler
  File "/home/jus/build/screeps-starter-python/env/lib/python3.7/site-packages/transcrypt/modules/org/transcrypt/compiler.py", line 2118
    self.visit_FunctionDef (node, async = True)
                                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "./screeps-starter-python/build.py", line 334, in <module>
    main()
  File "./screeps-starter-python/build.py", line 329, in main
    build(config)
  File "./screeps-starter-python/build.py", line 199, in build
    run_transcrypt(config)
  File "./screeps-starter-python/build.py", line 160, in run_transcrypt
    .format(ret, "' '".join(args), config.source_dir))
Exception: transcrypt failed. exit code: 1. command line '/home/jus/build/screeps-starter-python/env/bin/transcrypt' '-n' '-p' '.none' '-b' '/home/jus/build/screeps-starter-python/src/main.py'. working dir: '/home/jus/build/screeps-starter-python/src'.`

**Comment by d-ornen** [comment]
got it: the error was installing the python 3.7 libs, and launching script with 3.5 version.
