### ISSUE TITLE
python3 build.py fails on mac os running 12.6..8

### ISSUE THREAD

**Issue by Fau57** [daboross/screeps-starter-python#43]
im not sure if this issue is new or similar to the bin removed error previously posted if its the same thing ill just post a comment in the other issues post. This is also my first issues post so if i leave anything out please comment and ill edit the post. here is what my terminal spits out when i tried to python3 build.py. python3 isnt new on my system but node is, so perhaps thats the issue? anyway heres the terminal results:
Traceback (most recent call last):
  File "/Users/user/screeps-starter-python/build.py", line 437, in <module>
    main()
  File "/Users/user/screeps-starter-python/build.py", line 426, in main
    install_node_dependencies(config)
  File "/Users/user/screeps-starter-python/build.py", line 403, in install_node_dependencies
    if config.rollup_executable() is not None:
  File "/Users/user/screeps-starter-python/build.py", line 159, in rollup_executable
    for path in possible_rollup_binary_paths(self):
  File "/Users/user/screeps-starter-python/build.py", line 52, in possible_rollup_binary_paths
    raise Exception("npm bin failed. exit code: {}. command line '{}'. stderr: {}. stdout: {}"
Exception: npm bin failed. exit code: 1. command line '/usr/local/bin/npm' 'bin'. stderr: . stdout: Unknown command: "bin"

To see a list of supported npm commands, run:
  npm help

Thanks in advanced.

**Comment by FiddlerNeb** [comment]
also seeing this problem in windows
pip install --upgrade -r requirements.txt
![image](https://github.com/daboross/screeps-starter-python/assets/9406934/ed13df3e-adb8-478d-bd83-96ce73c0ab8d)

**Comment by FiddlerNeb** [comment]
![image](https://github.com/daboross/screeps-starter-python/assets/9406934/81e82c3b-8d99-43f2-b8ab-391613aadb4d)

**Comment by FiddlerNeb** [comment]
figured out this issue! npm bin was depricated in npm +9.0, if you install Node.js <=16.20.2 you will get npm version <=8 
https://github.com/grafana/grafana/issues/59425

**Comment by l33tlinuxh4x0r** [comment]
https://github.com/daboross/screeps-starter-python/pull/48 fixes this issue.
