### ISSUE TITLE
python build.py

### ISSUE THREAD

**Issue by doubravap** [daboross/screeps-starter-python#46]
this same problem in python 3.12 and in conda python 3.11

d:\anaconda3\envs\screeps\Library\screeps-starter-python>python build.py
Traceback (most recent call last):
  File "d:\anaconda3\envs\screeps\Library\screeps-starter-python\build.py", line 437, in <module>
    main()
  File "d:\anaconda3\envs\screeps\Library\screeps-starter-python\build.py", line 426, in main
    install_node_dependencies(config)
  File "d:\anaconda3\envs\screeps\Library\screeps-starter-python\build.py", line 403, in install_node_dependencies
    if config.rollup_executable() is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\envs\screeps\Library\screeps-starter-python\build.py", line 159, in rollup_executable
    for path in possible_rollup_binary_paths(self):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\envs\screeps\Library\screeps-starter-python\build.py", line 52, in possible_rollup_binary_paths
    raise Exception("npm bin failed. exit code: {}. command line '{}'. stderr: {}. stdout: {}"
Exception: npm bin failed. exit code: 1. command line 'C:\Program Files\nodejs\npm.CMD' 'bin'. stderr: . stdout: Unknown command: "bin"

To see a list of supported npm commands, run:
  npm help

**Comment by StardustRevelry** [comment]
npm bin was depricated in npm +9.0, if you install Node.js <=16.20.2 you will get npm version <=8
https://github.com/grafana/grafana/issues/59425

**Comment by l33tlinuxh4x0r** [comment]
https://github.com/daboross/screeps-starter-python/pull/48 fixes this issue.
